apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi